const defaultData={study:[{name:"Khan Academy",url:"https://www.khanacademy.org",icon:"📚",desc:"Free lessons and practice."},{name:"Coursera",url:"https://www.coursera.org",icon:"🎓",desc:"Courses from universities and companies."},{name:"YouTube Learning",url:"https://www.youtube.com",icon:"▶️",desc:"Tutorials, lectures and explainers."},{name:"Google Classroom",url:"https://classroom.google.com",icon:"📝",desc:"Classes, assignments and materials."}],games:[{name:"Steam",url:"https://store.steampowered.com",icon:"🎮",desc:"Game library shortcut."},{name:"Epic Games",url:"https://store.epicgames.com",icon:"⚡",desc:"Store and launcher shortcut."},{name:"Xbox",url:"https://www.xbox.com",icon:"🟩",desc:"Xbox web destination."},{name:"PlayStation",url:"https://www.playstation.com",icon:"🎯",desc:"PlayStation destination."}]};
let data=JSON.parse(localStorage.getItem("sgh-web")||"null")||structuredClone(defaultData);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem("sgh-web",JSON.stringify(data));render()}
function go(v){$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$$(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v))}
function openUrl(url){window.open(url,"_blank","noopener,noreferrer")}
function card(item,type){return `<article class="card"><div><div class="icon">${item.icon}</div><h3>${item.name}</h3><p>${item.desc}</p></div><div class="row"><span class="badge">${type==="study"?"Study":"Web shortcut"}</span><a class="link" href="${item.url}" target="_blank" rel="noreferrer">Open ↗</a></div></article>`}
function gameCard(item){return `<article class="game"><div class="icon">${item.icon}</div><h3>${item.name}</h3><p>${item.desc}</p><div class="row"><span class="badge">Web edition</span><a class="link" href="${item.url}" target="_blank" rel="noreferrer">Open ↗</a></div></article>`}
function render(){const fav=0;$("#platformCount").textContent=data.study.length;$("#gameCount").textContent=data.games.length;$("#favoriteCount").textContent=fav;$("#quickCards").innerHTML=data.study.slice(0,4).map(x=>card(x,"study")).join("");$("#studyCards").innerHTML=data.study.map(x=>card(x,"study")).join("");$("#quickGames").innerHTML=data.games.slice(0,4).map(gameCard).join("");$("#gamesGrid").innerHTML=data.games.map(gameCard).join("")}
$$(".tab").forEach(b=>b.addEventListener("click",()=>go(b.dataset.view)));$$("[data-view-btn]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.viewBtn)));$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");document.body.classList.toggle("light");};$("#modeSelect").onchange=e=>{document.body.classList.remove("light","dark");if(e.target.value!=="soft")document.body.classList.add(e.target.value)};$("#resetBtn").onclick=()=>{data=structuredClone(defaultData);localStorage.removeItem("sgh-web");render()};
const modal=$("#modal"), title=$("#modalTitle"), name=$("#nameInput"), url=$("#urlInput");function openModal(t){title.textContent=t;name.value="";url.value="";modal.classList.add("open");name.focus()}$("#addStudyBtn").onclick=()=>openModal("Add study link");$("#addGameBtn").onclick=()=>openModal("Add game shortcut");$("#closeModal").onclick=()=>modal.classList.remove("open");$("#saveModal").onclick=()=>{const n=name.value.trim(),u=url.value.trim();if(!n||!/^https?:\\/\\//i.test(u))return alert("Please enter a name and a valid http(s) URL.");data.study.push({name:n,url:u,icon:"🔗",desc:"Custom link"});modal.classList.remove("open");save()};render();